### ISSUE TITLE
Issue with Add-CrmSolutionComponent

### ISSUE THREAD

**Issue by ArsenAghajanyan** [AMSoftwareNL/crmpowershell#17]
Hi,

I'm getting this kind of error "Input field type 'Boolean' does not match expected type 'String[]' for field 'IncludedComponentSettingsValues'" when trying to add a component to the solution. The way I do this is I use Get-CrmWebresource and Get-CrmSolution cmdlets to get the GUIDs of the solution and web resource. After that, I use these GUIDs to add the component to the solution.

Thanks,
Regards Arsen.

**Comment by AMSoftwareNL** [comment]
Fixed in v1.4.0.1
