### ISSUE TITLE
FetchXml with aggregate fails on PagingCookie

### ISSUE THREAD

**Issue by KKreutzkamp** [AMSoftwareNL/crmpowershell#19]
Steps to reproduce
------------------
Execute the following script:
`$contacts = Get-CrmContent -FetchXml '<fetch aggregate="true"><entity name="contact"/></fetch>'`
Expected behavior
-----------------
$contacts contains all requested contacts.

Actual behavior
---------------
The following exception is thrown:
Get-CrmContent : The Top.Count = 5000 can't be specified with pagingInfo
At line:3 char:13
+ $contacts = Get-CrmContent -FetchXml $fetchxml
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-CrmContent], FaultException`1
    + FullyQualifiedErrorId : AMSoftware.Crm.PowerShell.Commands.Content.GetContentCommand

Environment data
----------------

version: 1.4.0.1

**Comment by AMSoftwareNL** [comment]
Could you include the FetchXML used? And does the expected result of the FetchXML return more than 5000 rows?

Tested with the following XML and behaves as expected:
```
<fetch mapping="logical" output-format="xml-platform" version="1.0" distinct="false">
  <entity name="contact">
    <attribute name="fullname" />
    <attribute name="telephone1" />
    <attribute name="contactid" />
    <order descending="false" attribute="fullname" />
  </entity>
</fetch>
```


With the following commands:
```
[xml]$fetch = Get-Content C:\Temp\FetchXML.xml -Raw
Get-CrmContent -FetchXml $fetch -IncludeTotalCount
```

**Comment by AMSoftwareNL** [comment]
Related to #22 FetchXML with aggregate executes as query without aggregate

**Comment by AMSoftwareNL** [comment]
Handling of FetchXML goes wrong on translation from XML to QueryExpression. This also looses aggregations.
No longer translate to QueryExpression (just keep XML) and added paging in the XML
