### ISSUE TITLE
Connect-CrmOrganization throws error

### ISSUE THREAD

**Issue by CMeyer-work** [AMSoftwareNL/crmpowershell#32]
Steps to reproduce
Using Connect-CrmOrganzation with parameter -Connectionstring throws error 

Connect-CrmOrganization : Method not found: 'Microsoft.Xrm.Sdk.Discovery.OrganizationDetail Microsoft.Xrm.Tooling.Connector.CrmServiceClient.get_OrganizationDetail()'.

I tried it also with parameter -Connection but the same behaviour. 
I checked also the dependency Microsoft.Xrm.Tooling.CrmConnector.PowerShell and using it in version 3.3.0.928.
I´m not sure if there is another dependency which I can check before. 

Expected behavior
Connect-CrmOrganization call is successful

Actual behavior
Connect-CrmOrganization call throws error

Environment data
----------------

v2.0.0.0

**Comment by CMeyer-work** [comment]
Seems to be a problem with Connection String itself

**Comment by AMSoftwareNL** [comment]
Good to hear you found the issue. I will take a look at the logic and error handling of Connect-CrmOrganization for the next update to make sure this is done correctly, and the error provides useful information when connection fails. **See #33** 

Thanks for using and improving the library!

**Comment by CMeyer-work** [comment]
Hi Arjan, just one update for this issue:
We faced another issue regarding the call of Connect-CrmOrganization and found out that the Microsoft.Xrm.Sdk.dll you are using has a lower version than others cmdlets
Your version is 9.0.45.2156 and from Xrm.Framework.CI.PowerShell.Cmdlets in version 9.1.0.2 they are using SDK dll in version 9.0.45.2282. With this version of the Microsoft.Xrm.Sdk.dll you are getting the error mentioned in the issue. 
So it depends in which order cmdlets are used in the powershell scripts if the error occurs or not.
