### ISSUE TITLE
When connecting to a Dynamics 365 crm Online (Office 365) on Version 9.0.0.3172 I get: "metadata contains a reference that cannot be resolved"

### ISSUE THREAD

**Issue by RichieRoxx** [AMSoftwareNL/crmpowershell#5]
When connecting to a Dynamics 365 crm Online (Office 365) on Version 9.0.0.3172 I get:
"metadata contains a reference that cannot be resolved"

Steps to reproduce
------------------

Connect-CrmOrganization $OrgUniqueName 

Expected behavior
-----------------
successfull connection to org

Actual behavior
---------------

Error: "metadata contains a reference that cannot be resolved"
Environment data
----------------

Dynamics 365 crm Online (Office 365) on Version 9.0.0.3172

v1.3.0.0

**Comment by AMSoftwareNL** [comment]
It appears the Dynamics 365 CRM v9.0 doesn't have a compatible SDK for the webservices. The SDK it self isn't available for download. The NuGet packages are available, but even with those the error occurs. 
I'm in the proces of re-writing the whole solution to use the oData services so it no longer depends on the SDK (webservices) but this will take some time.

**Comment by RichieRoxx** [comment]
Cool, thanks for the update! Your effort is appreciated!

**Comment by AMSoftwareNL** [comment]
Solved in release v1.3.1 by forcing the use of TLS1.2.

**Comment by RichieRoxx** [comment]
works like a charm, thank you!!!!
